services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=mydb
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 1234:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d mydb" ]
      interval: 10s
      retries: 10
  web:
    build: .
    working_dir: /app/cats_website
    entrypoint: ./entrypoint.sh
    volumes:
      - static_volume:/app/cats_website/staticfiles
    expose:
      - 8000
    environment:
      - DJANGO_SECRET_KEY='django-insecure-h6-i*7drtdzjdt2na_utl8muqen!^$o*&p=)au^*2usu$go-@9'
      - POSTGRES_HOST=db
      - POSTGRES_DB_NAME=mydb
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_PORT=5432
    depends_on:
      db:
        condition: service_healthy
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/app/cats_website/staticfiles
    ports:
      - 1337:80
    depends_on:
      - web
volumes:
  db_data:
  static_volume:
