# Generated by Django 5.1.1 on 2024-10-01 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats_restapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='age',
            field=models.PositiveSmallIntegerField(verbose_name='Age in full months'),
        ),
    ]
