# Generated by Django 5.1.1 on 2024-10-01 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats_restapi', '0002_alter_cat_age'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cat',
            name='user',
        ),
        migrations.AddField(
            model_name='cat',
            name='name',
            field=models.CharField(default='Cat default', max_length=255, verbose_name='Cat name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cat',
            name='owner',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='cats_for_owner', to=settings.AUTH_USER_MODEL, verbose_name="Cat's owner"),
        ),
        migrations.AlterField(
            model_name='breed',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='cat',
            name='breed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cats_for_breed', to='cats_restapi.breed', to_field='name'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='color',
            field=models.CharField(max_length=100, verbose_name='Cat color'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='description',
            field=models.TextField(max_length=500, verbose_name='Cat description'),
        ),
    ]
