# Generated by Django 5.1.1 on 2024-10-02 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats_restapi', '0003_remove_cat_user_cat_name_cat_owner_alter_breed_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='breed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cats_for_breed', to='cats_restapi.breed'),
        ),
    ]
