# Generated by Django 5.1.1 on 2024-10-04 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cats_restapi', '0004_alter_cat_breed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catrating',
            old_name='user',
            new_name='owner',
        ),
    ]
