# Generated by Django 5.1.1 on 2024-10-04 16:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cats_restapi', '0005_rename_user_catrating_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='catrating',
            old_name='owner',
            new_name='rated_by_user',
        ),
        migrations.AlterUniqueTogether(
            name='catrating',
            unique_together={('cat', 'rated_by_user')},
        ),
    ]
