# Generated by Django 5.1.1 on 2024-10-04 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats_restapi', '0006_rename_owner_catrating_rated_by_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catrating',
            name='rating',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='Rating in range from 1 to 5'),
        ),
    ]
